### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by cyclone125** [phortx/Raspberry-Pi-Setup-Guide#11]
Nice guide, thanks. I have a couple of small additions to it.
In sections "11.1 Increase SD card lifetime" you have
`/dev/root  /  ext4  defaults,nodiratime,noatime,discard  0  0`
So, `noatime` implies `nodiratime`. [You do not need to specify both.](https://lwn.net/Articles/244941/)
Also, I think, it would be a good idea (may be, optional) to use F2FS instead of ext4 on SD card.
In "1. Setup the SD card":
`sudo apt-get install f2fs-tools`
`sudo mount -t f2fs /dev/sdX2 /mnt/root`
In text editor add `rootfstype=f2fs` to `/boot/cmdline.txt`
Change `fstab`: `/dev/mmcblk0p2 / f2fs defaults,noatime,discard 0 0`
etc.

**Comment by phortx** [comment]
Hi cyclone!

Thanks for the advice. They sound very reasonable and I'm always happy about contributions to this guide due to the fact that I don't use any Pi at the moment :)

Would you create a Pull Request?
