### ISSUE TITLE
Question: Why NTP vs systemd-timesyncd?

### ISSUE THREAD

**Issue by bcomnes** [phortx/Raspberry-Pi-Setup-Guide#4]
Great Guide!  Just curious why you decided to set up NTP when the system comes with `systemd-timesyncd` by default?

**Comment by phortx** [comment]
The reason is pretty simple: I just didn't know it ;)

Feel free to open a pull request to change that.

**Comment by bcomnes** [comment]
I wouldn't have a good argument against it other than that one is already on by default :P  Thanks for clarifying!
