### ISSUE TITLE
More systematic configuration

### ISSUE THREAD

**Issue by roolo** [phortx/Raspberry-Pi-Setup-Guide#5]
Hi there,
I think I was doing something similar to what you do

https://github.com/roolo/provisioning-raspberry

It is set of declarations how the machine should look and then Ansible will make it happen.
Just be aware that my solution covers only your "2. Basic system setup"

**Comment by phortx** [comment]
Hi!

Yes, seems pretty similar. Actually this (my) guide trys to work independent from any automation solution like chef, ansible, however in order to allow everyone a quick start without diving into the complexity of deployment or provisioning automation systems :)
